---
- name: just force systemd to reload units (2.4 and above)
  systemd:
    daemon_reload: yes

- name: Enable etcd
  service: name=etcd enabled=yes
  when: etcd_enable == true

- name: Start etcd
  service: name=etcd state=started
  register: etcd_started
